//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программным средством.
//     Версия среды выполнения:4.0.20826.0
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создается повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalysisExcel.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAnalysisExcel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Добавить новую дату".
        /// </summary>
        internal static string AddNewDateButton {
            get {
                return ResourceManager.GetString("AddNewDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Среднее число проданных единиц".
        /// </summary>
        internal static string AverageOfUnitsSold {
            get {
                return ResourceManager.GetString("AverageOfUnitsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Средний доход".
        /// </summary>
        internal static string AverageProfit {
            get {
                return ResourceManager.GetString("AverageProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Средняя продажа".
        /// </summary>
        internal static string AverageSold {
            get {
                return ResourceManager.GetString("AverageSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Средние результаты".
        /// </summary>
        internal static string AveragesPivotTableName {
            get {
                return ResourceManager.GetString("AveragesPivotTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "создать незапланированный заказ".
        /// </summary>
        internal static string CreateUnscheduledOrderRecommendation {
            get {
                return ResourceManager.GetString("CreateUnscheduledOrderRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Текущий запас".
        /// </summary>
        internal static string CurrentInventoryHeader {
            get {
                return ResourceManager.GetString("CurrentInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Выполняет поиск локализованной строки, сходной со строкой "Необходимо ввести значения запасов на конец дня для всех сортов мороженого для {0:d}, прежде чем можно будет создать заказ или добавить новые данные по сбыту".
        /// </summary>
        internal static string DataIncompleteError {
            get {
                return ResourceManager.GetString("DataIncompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Дата".
        /// </summary>
        internal static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Дата поставки".
        /// </summary>
        internal static string DeliveryDateHeader {
            get {
                return ResourceManager.GetString("DeliveryDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Фактический запас на конец дня".
        /// </summary>
        internal static string EodInventoryHeader {
            get {
                return ResourceManager.GetString("EodInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Оцененный запас".
        /// </summary>
        internal static string EstimatedInventoryHeader {
            get {
                return ResourceManager.GetString("EstimatedInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Мороженое".
        /// </summary>
        internal static string IceCreamHeader {
            get {
                return ResourceManager.GetString("IceCreamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Запас".
        /// </summary>
        internal static string InventoryHeader {
            get {
                return ResourceManager.GetString("InventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Максимальный дневной оборот".
        /// </summary>
        internal static string MaxDailySalesHeader {
            get {
                return ResourceManager.GetString("MaxDailySalesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Чистый доход".
        /// </summary>
        internal static string NetGainHeader {
            get {
                return ResourceManager.GetString("NetGainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Дата заказа".
        /// </summary>
        internal static string OrderDateHeader {
            get {
                return ResourceManager.GetString("OrderDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Количество заказа".
        /// </summary>
        internal static string OrderQuantityHeader {
            get {
                return ResourceManager.GetString("OrderQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "З&amp;аказы".
        /// </summary>
        internal static string OrdersMenu {
            get {
                return ResourceManager.GetString("OrdersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Заказы".
        /// </summary>
        internal static string OrdersToolbar {
            get {
                return ResourceManager.GetString("OrdersToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Прибыль".
        /// </summary>
        internal static string ProfitHeader {
            get {
                return ResourceManager.GetString("ProfitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Планируемый запас".
        /// </summary>
        internal static string ProjectedInventoryHeader {
            get {
                return ResourceManager.GetString("ProjectedInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Планируемые продажи".
        /// </summary>
        internal static string ProjectedSalesHeader {
            get {
                return ResourceManager.GetString("ProjectedSalesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Рекомендация".
        /// </summary>
        internal static string RecommendationHeader {
            get {
                return ResourceManager.GetString("RecommendationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Продажи и доход".
        /// </summary>
        internal static string SalesAndProfitPivotTableName {
            get {
                return ResourceManager.GetString("SalesAndProfitPivotTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Сохранить данные".
        /// </summary>
        internal static string SaveDataButton {
            get {
                return ResourceManager.GetString("SaveDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Дата:".
        /// </summary>
        internal static string Sheet1DateLabel {
            get {
                return ResourceManager.GetString("Sheet1DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Запас".
        /// </summary>
        internal static string Sheet1Name {
            get {
                return ResourceManager.GetString("Sheet1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Управление запасами".
        /// </summary>
        internal static string Sheet1Title {
            get {
                return ResourceManager.GetString("Sheet1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Мороженое".
        /// </summary>
        internal static string Sheet2IceCreamLabel {
            get {
                return ResourceManager.GetString("Sheet2IceCreamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Подробные сведения".
        /// </summary>
        internal static string Sheet2Name {
            get {
                return ResourceManager.GetString("Sheet2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Подробные сведения о запасах".
        /// </summary>
        internal static string Sheet2Title {
            get {
                return ResourceManager.GetString("Sheet2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Продано".
        /// </summary>
        internal static string SoldHeader {
            get {
                return ResourceManager.GetString("SoldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Стандартное отклонение числа проданных единиц".
        /// </summary>
        internal static string StdDevOfUnitsSold {
            get {
                return ResourceManager.GetString("StdDevOfUnitsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Продано единиц".
        /// </summary>
        internal static string UnitsSoldHeader {
            get {
                return ResourceManager.GetString("UnitsSoldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Создать &amp;незапланированный заказ".
        /// </summary>
        internal static string UnscheduledMenu {
            get {
                return ResourceManager.GetString("UnscheduledMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Выполняет поиск локализованной строки, сходной со строкой "Расчетные затраты, связанные с незапланированным заказом по позициям недостаточного запаса, равны {0:.00}. Незапланированный заказ не рекомендуется".
        /// </summary>
        internal static string UnscheduledOrderNotRecommended {
            get {
                return ResourceManager.GetString("UnscheduledOrderNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной со строкой "Расчетная прибыль от незапланированного заказа по позициям недостаточного запаса равна {0:.00}".
        /// </summary>
        internal static string UnscheduledOrderRecommended {
            get {
                return ResourceManager.GetString("UnscheduledOrderRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Не удалось создать лист незапланированного заказа. Проверьте, что новый лист может быть добавлен в книгу и что не существует лист с именем {0}".
        /// </summary>
        internal static string UnscheduledOrderSheetCreationError {
            get {
                return ResourceManager.GetString("UnscheduledOrderSheetCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной со строкой "Незапланированный заказ: {0}".
        /// </summary>
        internal static string UnscheduledOrderSheetName {
            get {
                return ResourceManager.GetString("UnscheduledOrderSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Создать &amp;еженедельный заказ".
        /// </summary>
        internal static string WeeklyMenu {
            get {
                return ResourceManager.GetString("WeeklyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с "Не удалось создать лист еженедельного заказа. Проверьте, что новый лист может быть добавлен в книгу и что не существует лист с именем {0}".
        /// </summary>
        internal static string WeeklyOrderSheetCreationError {
            get {
                return ResourceManager.GetString("WeeklyOrderSheetCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной со строкой "Еженедельный заказ: {0}".
        /// </summary>
        internal static string WeeklyOrderSheetName {
            get {
                return ResourceManager.GetString("WeeklyOrderSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной со строкой "Лист с именем {0} уже существует".
        /// </summary>
        internal static string WorksheetExistsError {
            get {
                return ResourceManager.GetString("WorksheetExistsError", resourceCulture);
            }
        }
    }
}
