//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFileService")]
public interface IFileService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetSubDirectories", ReplyAction="http://tempuri.org/IFileService/GetSubDirectoriesResponse")]
    string[] GetSubDirectories(string directory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetFiles", ReplyAction="http://tempuri.org/IFileService/GetFilesResponse")]
    string[] GetFiles(string directory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/RetrieveFile", ReplyAction="http://tempuri.org/IFileService/RetrieveFileResponse")]
    int RetrieveFile(out byte[] bytes, string filename, int amountToRead);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IFileServiceChannel : IFileService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class FileServiceClient : System.ServiceModel.ClientBase<IFileService>, IFileService
{
    
    public FileServiceClient()
    {
    }
    
    public FileServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetSubDirectories(string directory)
    {
        return base.Channel.GetSubDirectories(directory);
    }
    
    public string[] GetFiles(string directory)
    {
        return base.Channel.GetFiles(directory);
    }
    
    public int RetrieveFile(out byte[] bytes, string filename, int amountToRead)
    {
        return base.Channel.RetrieveFile(out bytes, filename, amountToRead);
    }
}
