//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программным средством.
//     Версия среды выполнения:4.0.20824.0
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создается повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiManagerOutlookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiManagerOutlookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap espressoCup {
            get {
                object obj = ResourceManager.GetObject("espressoCup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap espressoCup_tall {
            get {
                object obj = ResourceManager.GetObject("espressoCup_tall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SimpleFormRegionOfs {
            get {
                object obj = ResourceManager.GetObject("SimpleFormRegionOfs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FormRegion xmlns=&quot;http://schemas.microsoft.com/office/outlook/12/formregion.xsd&quot;&gt;
        ///  &lt;formRegionType&gt;separate&lt;/formRegionType&gt;
        ///  &lt;formRegionName&gt;UIM&lt;/formRegionName&gt;
        ///  &lt;showInspectorCompose&gt;true&lt;/showInspectorCompose&gt;
        ///  &lt;showInspectorRead&gt;true&lt;/showInspectorRead&gt;
        ///  &lt;showReadingPane&gt;false&lt;/showReadingPane&gt;
        ///  &lt;icons&gt;
        ///    &lt;page&gt;addin&lt;/page&gt;
        ///  &lt;/icons&gt;
        ///&lt;/FormRegion&gt;.
        /// </summary>
        internal static string SimpleFormRegionXml {
            get {
                return ResourceManager.GetString("SimpleFormRegionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; 
        ///          onLoad=&quot;OnLoad&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///		&lt;tab idMso=&quot;TabAddIns&quot;&gt;
        ///			&lt;group id=&quot;uimGroup&quot; label=&quot;UI Manager&quot;&gt;
        ///				&lt;toggleButton id=&quot;toggleTaskPane&quot;
        ///							  label=&quot;TaskPane&quot;
        ///							  imageMso=&quot;ControlLayoutStacked&quot;
        ///							  size=&quot;large&quot;
        ///							  onAction=&quot;OnToggleTaskPane&quot; /&gt;
        ///			&lt;/group&gt;
        ///		&lt;/tab&gt;
        ///    &lt;/tabs&gt;
        ///  &lt;/ribbon&gt;
        ///&lt;/customUI&gt;
        ///.
        /// </summary>
        internal static string SimpleRibbon {
            get {
                return ResourceManager.GetString("SimpleRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованной строки, сходной с &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; 
        ///          onLoad=&quot;OnLoad&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///		&lt;tab idMso=&quot;TabAddIns&quot;&gt;
        ///			&lt;group id=&quot;uimGroup&quot; label=&quot;Диспетчер пользовательского интерфейса&quot;&gt;
        ///				&lt;toggleButton id=&quot;toggleTaskPane&quot;
        ///							  label=&quot;TaskPane&quot;
        ///							  imageMso=&quot;ControlLayoutStacked&quot;
        ///							  size=&quot;large&quot;
        ///							  onAction=&quot;OnToggleTaskPane&quot; /&gt;
        ///			&lt;/group&gt;
        ///			&lt;group id=&quot;mailServiceGroup&quot;
        ///				   label=&quot;Add-in Services&quot;
        ///				   getVisible=&quot;GetVisible&quot;&gt;
        ///				&lt;button id=&quot;sendList&quot;
        ///					 [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string TaskRibbon {
            get {
                return ResourceManager.GetString("TaskRibbon", resourceCulture);
            }
        }
    }
}
